name: Build and Deploy

on:
  push:
    branches:
      - main # 监听 main 分支的推送

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.18.3" # 根据需要选择合适的 Node.js 版本

      - name: Install dependencies
        run: npm install yarn -g
      
      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # 构建后的静态文件目录
